/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ev9_path_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};

/* ev9_path_dyn_disc_phi_fun:(i0[4],i1[2],i2[4])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=arg[0]? arg[0][0] : 0;
  a01=5.0614268145188261e-02;
  a02=arg[0]? arg[0][2] : 0;
  a03=1.9855071751231912e-02;
  a04=arg[0]? arg[0][3] : 0;
  a05=arg[2]? arg[2][0] : 0;
  a06=30.;
  a05=(a05/a06);
  a06=arg[1]? arg[1][1] : 0;
  a05=(a05*a06);
  a06=(a04*a05);
  a06=(a03*a06);
  a06=(a02+a06);
  a07=3.9422387424656747e-04;
  a08=arg[1]? arg[1][0] : 0;
  a09=casadi_sq(a05);
  a09=(a08*a09);
  a09=(a07*a09);
  a10=2.;
  a09=(a09/a10);
  a06=(a06+a09);
  a06=cos(a06);
  a06=(a01*a06);
  a09=1.1119051722668723e-01;
  a11=1.0166676129318664e-01;
  a12=(a04*a05);
  a12=(a11*a12);
  a12=(a02+a12);
  a13=1.0336130351845793e-02;
  a14=casadi_sq(a05);
  a14=(a08*a14);
  a14=(a13*a14);
  a14=(a14/a10);
  a12=(a12+a14);
  a12=cos(a12);
  a12=(a09*a12);
  a06=(a06+a12);
  a12=1.5685332293894358e-01;
  a14=2.3723379504183550e-01;
  a15=(a04*a05);
  a15=(a14*a15);
  a15=(a02+a15);
  a16=5.6279873509951617e-02;
  a17=casadi_sq(a05);
  a17=(a08*a17);
  a17=(a16*a17);
  a17=(a17/a10);
  a15=(a15+a17);
  a15=cos(a15);
  a15=(a12*a15);
  a06=(a06+a15);
  a15=1.8134189168918091e-01;
  a17=4.0828267875217505e-01;
  a18=(a04*a05);
  a18=(a17*a18);
  a18=(a02+a18);
  a19=1.6669474576905177e-01;
  a20=casadi_sq(a05);
  a20=(a08*a20);
  a20=(a19*a20);
  a20=(a20/a10);
  a18=(a18+a20);
  a18=cos(a18);
  a18=(a15*a18);
  a06=(a06+a18);
  a18=5.9171732124782495e-01;
  a20=(a04*a05);
  a20=(a18*a20);
  a20=(a02+a20);
  a21=3.5012938826470169e-01;
  a22=casadi_sq(a05);
  a22=(a08*a22);
  a22=(a21*a22);
  a22=(a22/a10);
  a20=(a20+a22);
  a20=cos(a20);
  a20=(a15*a20);
  a06=(a06+a20);
  a20=7.6276620495816450e-01;
  a22=(a04*a05);
  a22=(a20*a22);
  a22=(a02+a22);
  a23=5.8181228342628055e-01;
  a24=casadi_sq(a05);
  a24=(a08*a24);
  a24=(a23*a24);
  a24=(a24/a10);
  a22=(a22+a24);
  a22=cos(a22);
  a22=(a12*a22);
  a06=(a06+a22);
  a22=8.9833323870681336e-01;
  a24=(a04*a05);
  a24=(a22*a24);
  a24=(a02+a24);
  a25=8.0700260776547250e-01;
  a26=casadi_sq(a05);
  a26=(a08*a26);
  a26=(a25*a26);
  a26=(a26/a10);
  a24=(a24+a26);
  a24=cos(a24);
  a24=(a09*a24);
  a06=(a06+a24);
  a24=9.8014492824876809e-01;
  a26=(a04*a05);
  a26=(a24*a26);
  a26=(a02+a26);
  a27=9.6068408037178277e-01;
  a28=casadi_sq(a05);
  a28=(a08*a28);
  a28=(a27*a28);
  a28=(a28/a10);
  a26=(a26+a28);
  a26=cos(a26);
  a26=(a01*a26);
  a06=(a06+a26);
  a06=(a06*a05);
  a00=(a00+a06);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a06=(a04*a05);
  a03=(a03*a06);
  a03=(a02+a03);
  a06=casadi_sq(a05);
  a06=(a08*a06);
  a07=(a07*a06);
  a07=(a07/a10);
  a03=(a03+a07);
  a03=sin(a03);
  a03=(a01*a03);
  a07=(a04*a05);
  a11=(a11*a07);
  a11=(a02+a11);
  a07=casadi_sq(a05);
  a07=(a08*a07);
  a13=(a13*a07);
  a13=(a13/a10);
  a11=(a11+a13);
  a11=sin(a11);
  a11=(a09*a11);
  a03=(a03+a11);
  a11=(a04*a05);
  a14=(a14*a11);
  a14=(a02+a14);
  a11=casadi_sq(a05);
  a11=(a08*a11);
  a16=(a16*a11);
  a16=(a16/a10);
  a14=(a14+a16);
  a14=sin(a14);
  a14=(a12*a14);
  a03=(a03+a14);
  a14=(a04*a05);
  a17=(a17*a14);
  a17=(a02+a17);
  a14=casadi_sq(a05);
  a14=(a08*a14);
  a19=(a19*a14);
  a19=(a19/a10);
  a17=(a17+a19);
  a17=sin(a17);
  a17=(a15*a17);
  a03=(a03+a17);
  a17=(a04*a05);
  a18=(a18*a17);
  a18=(a02+a18);
  a17=casadi_sq(a05);
  a17=(a08*a17);
  a21=(a21*a17);
  a21=(a21/a10);
  a18=(a18+a21);
  a18=sin(a18);
  a15=(a15*a18);
  a03=(a03+a15);
  a15=(a04*a05);
  a20=(a20*a15);
  a20=(a02+a20);
  a15=casadi_sq(a05);
  a15=(a08*a15);
  a23=(a23*a15);
  a23=(a23/a10);
  a20=(a20+a23);
  a20=sin(a20);
  a12=(a12*a20);
  a03=(a03+a12);
  a12=(a04*a05);
  a22=(a22*a12);
  a22=(a02+a22);
  a12=casadi_sq(a05);
  a12=(a08*a12);
  a25=(a25*a12);
  a25=(a25/a10);
  a22=(a22+a25);
  a22=sin(a22);
  a09=(a09*a22);
  a03=(a03+a09);
  a09=(a04*a05);
  a24=(a24*a09);
  a24=(a02+a24);
  a09=casadi_sq(a05);
  a09=(a08*a09);
  a27=(a27*a09);
  a27=(a27/a10);
  a24=(a24+a27);
  a24=sin(a24);
  a01=(a01*a24);
  a03=(a03+a01);
  a03=(a03*a05);
  a00=(a00+a03);
  if (res[0]!=0) res[0][1]=a00;
  a00=(a04*a05);
  a02=(a02+a00);
  a00=casadi_sq(a05);
  a00=(a08*a00);
  a00=(a00/a10);
  a02=(a02+a00);
  if (res[0]!=0) res[0][2]=a02;
  a08=(a08*a05);
  a04=(a04+a08);
  if (res[0]!=0) res[0][3]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ev9_path_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int ev9_path_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ev9_path_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ev9_path_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ev9_path_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ev9_path_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ev9_path_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
