/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ev9_path_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[24] = 
  {6, 4, 0, 5, 10, 14, 17, 0,
  1, 2, 4, 5, 0, 1, 3, 4,
  5, 0, 1, 4, 5, 0, 1, 5};

/* ev9_path_dyn_disc_phi_fun_jac:(i0[4],i1[2],i2[4])->(o0[4],o1[6x4,17nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=arg[0]? arg[0][0] : 0;
  a01=5.0614268145188261e-02;
  a02=arg[0]? arg[0][2] : 0;
  a03=1.9855071751231912e-02;
  a04=arg[0]? arg[0][3] : 0;
  a05=arg[2]? arg[2][0] : 0;
  a06=30.;
  a05=(a05/a06);
  a06=arg[1]? arg[1][1] : 0;
  a06=(a05*a06);
  a07=(a04*a06);
  a07=(a03*a07);
  a07=(a02+a07);
  a08=3.9422387424656747e-04;
  a09=arg[1]? arg[1][0] : 0;
  a10=casadi_sq(a06);
  a11=(a09*a10);
  a11=(a08*a11);
  a12=2.;
  a11=(a11/a12);
  a07=(a07+a11);
  a11=cos(a07);
  a11=(a01*a11);
  a13=1.1119051722668723e-01;
  a14=1.0166676129318664e-01;
  a15=(a04*a06);
  a15=(a14*a15);
  a15=(a02+a15);
  a16=1.0336130351845793e-02;
  a17=casadi_sq(a06);
  a18=(a09*a17);
  a18=(a16*a18);
  a18=(a18/a12);
  a15=(a15+a18);
  a18=cos(a15);
  a18=(a13*a18);
  a11=(a11+a18);
  a18=1.5685332293894358e-01;
  a19=2.3723379504183550e-01;
  a20=(a04*a06);
  a20=(a19*a20);
  a20=(a02+a20);
  a21=5.6279873509951617e-02;
  a22=casadi_sq(a06);
  a23=(a09*a22);
  a23=(a21*a23);
  a23=(a23/a12);
  a20=(a20+a23);
  a23=cos(a20);
  a23=(a18*a23);
  a11=(a11+a23);
  a23=1.8134189168918091e-01;
  a24=4.0828267875217505e-01;
  a25=(a04*a06);
  a25=(a24*a25);
  a25=(a02+a25);
  a26=1.6669474576905177e-01;
  a27=casadi_sq(a06);
  a28=(a09*a27);
  a28=(a26*a28);
  a28=(a28/a12);
  a25=(a25+a28);
  a28=cos(a25);
  a28=(a23*a28);
  a11=(a11+a28);
  a28=5.9171732124782495e-01;
  a29=(a04*a06);
  a29=(a28*a29);
  a29=(a02+a29);
  a30=3.5012938826470169e-01;
  a31=casadi_sq(a06);
  a32=(a09*a31);
  a32=(a30*a32);
  a32=(a32/a12);
  a29=(a29+a32);
  a32=cos(a29);
  a32=(a23*a32);
  a11=(a11+a32);
  a32=7.6276620495816450e-01;
  a33=(a04*a06);
  a33=(a32*a33);
  a33=(a02+a33);
  a34=5.8181228342628055e-01;
  a35=casadi_sq(a06);
  a36=(a09*a35);
  a36=(a34*a36);
  a36=(a36/a12);
  a33=(a33+a36);
  a36=cos(a33);
  a36=(a18*a36);
  a11=(a11+a36);
  a36=8.9833323870681336e-01;
  a37=(a04*a06);
  a37=(a36*a37);
  a37=(a02+a37);
  a38=8.0700260776547250e-01;
  a39=casadi_sq(a06);
  a40=(a09*a39);
  a40=(a38*a40);
  a40=(a40/a12);
  a37=(a37+a40);
  a40=cos(a37);
  a40=(a13*a40);
  a11=(a11+a40);
  a40=9.8014492824876809e-01;
  a41=(a04*a06);
  a41=(a40*a41);
  a41=(a02+a41);
  a42=9.6068408037178277e-01;
  a43=casadi_sq(a06);
  a44=(a09*a43);
  a44=(a42*a44);
  a44=(a44/a12);
  a41=(a41+a44);
  a44=cos(a41);
  a44=(a01*a44);
  a11=(a11+a44);
  a44=(a11*a06);
  a00=(a00+a44);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a44=(a04*a06);
  a44=(a03*a44);
  a44=(a02+a44);
  a45=casadi_sq(a06);
  a46=(a09*a45);
  a46=(a08*a46);
  a46=(a46/a12);
  a44=(a44+a46);
  a46=sin(a44);
  a46=(a01*a46);
  a47=(a04*a06);
  a47=(a14*a47);
  a47=(a02+a47);
  a48=casadi_sq(a06);
  a49=(a09*a48);
  a49=(a16*a49);
  a49=(a49/a12);
  a47=(a47+a49);
  a49=sin(a47);
  a49=(a13*a49);
  a46=(a46+a49);
  a49=(a04*a06);
  a49=(a19*a49);
  a49=(a02+a49);
  a50=casadi_sq(a06);
  a51=(a09*a50);
  a51=(a21*a51);
  a51=(a51/a12);
  a49=(a49+a51);
  a51=sin(a49);
  a51=(a18*a51);
  a46=(a46+a51);
  a51=(a04*a06);
  a51=(a24*a51);
  a51=(a02+a51);
  a52=casadi_sq(a06);
  a53=(a09*a52);
  a53=(a26*a53);
  a53=(a53/a12);
  a51=(a51+a53);
  a53=sin(a51);
  a53=(a23*a53);
  a46=(a46+a53);
  a53=(a04*a06);
  a53=(a28*a53);
  a53=(a02+a53);
  a54=casadi_sq(a06);
  a55=(a09*a54);
  a55=(a30*a55);
  a55=(a55/a12);
  a53=(a53+a55);
  a55=sin(a53);
  a55=(a23*a55);
  a46=(a46+a55);
  a55=(a04*a06);
  a55=(a32*a55);
  a55=(a02+a55);
  a56=casadi_sq(a06);
  a57=(a09*a56);
  a57=(a34*a57);
  a57=(a57/a12);
  a55=(a55+a57);
  a57=sin(a55);
  a57=(a18*a57);
  a46=(a46+a57);
  a57=(a04*a06);
  a57=(a36*a57);
  a57=(a02+a57);
  a58=casadi_sq(a06);
  a59=(a09*a58);
  a59=(a38*a59);
  a59=(a59/a12);
  a57=(a57+a59);
  a59=sin(a57);
  a59=(a13*a59);
  a46=(a46+a59);
  a59=(a04*a06);
  a59=(a40*a59);
  a59=(a02+a59);
  a60=casadi_sq(a06);
  a61=(a09*a60);
  a61=(a42*a61);
  a61=(a61/a12);
  a59=(a59+a61);
  a61=sin(a59);
  a61=(a01*a61);
  a46=(a46+a61);
  a61=(a46*a06);
  a00=(a00+a61);
  if (res[0]!=0) res[0][1]=a00;
  a00=(a04*a06);
  a02=(a02+a00);
  a00=casadi_sq(a06);
  a61=(a09*a00);
  a61=(a61/a12);
  a02=(a02+a61);
  if (res[0]!=0) res[0][2]=a02;
  a02=(a09*a06);
  a02=(a04+a02);
  if (res[0]!=0) res[0][3]=a02;
  a07=sin(a07);
  a02=5.0000000000000000e-01;
  a10=(a08*a10);
  a10=(a02*a10);
  a10=(a07*a10);
  a10=(a01*a10);
  a15=sin(a15);
  a17=(a16*a17);
  a17=(a02*a17);
  a17=(a15*a17);
  a17=(a13*a17);
  a10=(a10+a17);
  a20=sin(a20);
  a22=(a21*a22);
  a22=(a02*a22);
  a22=(a20*a22);
  a22=(a18*a22);
  a10=(a10+a22);
  a25=sin(a25);
  a27=(a26*a27);
  a27=(a02*a27);
  a27=(a25*a27);
  a27=(a23*a27);
  a10=(a10+a27);
  a29=sin(a29);
  a31=(a30*a31);
  a31=(a02*a31);
  a31=(a29*a31);
  a31=(a23*a31);
  a10=(a10+a31);
  a33=sin(a33);
  a35=(a34*a35);
  a35=(a02*a35);
  a35=(a33*a35);
  a35=(a18*a35);
  a10=(a10+a35);
  a37=sin(a37);
  a39=(a38*a39);
  a39=(a02*a39);
  a39=(a37*a39);
  a39=(a13*a39);
  a10=(a10+a39);
  a41=sin(a41);
  a43=(a42*a43);
  a43=(a02*a43);
  a43=(a41*a43);
  a43=(a01*a43);
  a10=(a10+a43);
  a10=(a06*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][0]=a10;
  a11=(a11*a05);
  a10=(a04*a05);
  a10=(a03*a10);
  a43=(a06+a06);
  a43=(a43*a05);
  a43=(a09*a43);
  a43=(a08*a43);
  a43=(a02*a43);
  a10=(a10+a43);
  a10=(a07*a10);
  a10=(a01*a10);
  a43=(a04*a05);
  a43=(a14*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a16*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a15*a43);
  a43=(a13*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a19*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a21*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a20*a43);
  a43=(a18*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a24*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a26*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a25*a43);
  a43=(a23*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a28*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a30*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a29*a43);
  a43=(a23*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a32*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a34*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a33*a43);
  a43=(a18*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a36*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a38*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a37*a43);
  a43=(a13*a43);
  a10=(a10+a43);
  a43=(a04*a05);
  a43=(a40*a43);
  a39=(a06+a06);
  a39=(a39*a05);
  a39=(a09*a39);
  a39=(a42*a39);
  a39=(a02*a39);
  a43=(a43+a39);
  a43=(a41*a43);
  a43=(a01*a43);
  a10=(a10+a43);
  a10=(a06*a10);
  a11=(a11-a10);
  if (res[1]!=0) res[1][1]=a11;
  a11=1.;
  if (res[1]!=0) res[1][2]=a11;
  a10=(a01*a07);
  a43=(a13*a15);
  a10=(a10+a43);
  a43=(a18*a20);
  a10=(a10+a43);
  a43=(a23*a25);
  a10=(a10+a43);
  a43=(a23*a29);
  a10=(a10+a43);
  a43=(a18*a33);
  a10=(a10+a43);
  a43=(a13*a37);
  a10=(a10+a43);
  a43=(a01*a41);
  a10=(a10+a43);
  a10=(a06*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][3]=a10;
  a10=(a03*a06);
  a07=(a07*a10);
  a07=(a01*a07);
  a10=(a14*a06);
  a15=(a15*a10);
  a15=(a13*a15);
  a07=(a07+a15);
  a15=(a19*a06);
  a20=(a20*a15);
  a20=(a18*a20);
  a07=(a07+a20);
  a20=(a24*a06);
  a25=(a25*a20);
  a25=(a23*a25);
  a07=(a07+a25);
  a25=(a28*a06);
  a29=(a29*a25);
  a29=(a23*a29);
  a07=(a07+a29);
  a29=(a32*a06);
  a33=(a33*a29);
  a33=(a18*a33);
  a07=(a07+a33);
  a33=(a36*a06);
  a37=(a37*a33);
  a37=(a13*a37);
  a07=(a07+a37);
  a37=(a40*a06);
  a41=(a41*a37);
  a41=(a01*a41);
  a07=(a07+a41);
  a07=(a06*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][4]=a07;
  a44=cos(a44);
  a45=(a08*a45);
  a45=(a02*a45);
  a45=(a44*a45);
  a45=(a01*a45);
  a47=cos(a47);
  a48=(a16*a48);
  a48=(a02*a48);
  a48=(a47*a48);
  a48=(a13*a48);
  a45=(a45+a48);
  a49=cos(a49);
  a50=(a21*a50);
  a50=(a02*a50);
  a50=(a49*a50);
  a50=(a18*a50);
  a45=(a45+a50);
  a51=cos(a51);
  a52=(a26*a52);
  a52=(a02*a52);
  a52=(a51*a52);
  a52=(a23*a52);
  a45=(a45+a52);
  a53=cos(a53);
  a54=(a30*a54);
  a54=(a02*a54);
  a54=(a53*a54);
  a54=(a23*a54);
  a45=(a45+a54);
  a55=cos(a55);
  a56=(a34*a56);
  a56=(a02*a56);
  a56=(a55*a56);
  a56=(a18*a56);
  a45=(a45+a56);
  a57=cos(a57);
  a58=(a38*a58);
  a58=(a02*a58);
  a58=(a57*a58);
  a58=(a13*a58);
  a45=(a45+a58);
  a59=cos(a59);
  a60=(a42*a60);
  a60=(a02*a60);
  a60=(a59*a60);
  a60=(a01*a60);
  a45=(a45+a60);
  a45=(a06*a45);
  if (res[1]!=0) res[1][5]=a45;
  a45=(a04*a05);
  a45=(a03*a45);
  a60=(a06+a06);
  a60=(a60*a05);
  a60=(a09*a60);
  a08=(a08*a60);
  a08=(a02*a08);
  a45=(a45+a08);
  a45=(a44*a45);
  a45=(a01*a45);
  a08=(a04*a05);
  a08=(a14*a08);
  a60=(a06+a06);
  a60=(a60*a05);
  a60=(a09*a60);
  a16=(a16*a60);
  a16=(a02*a16);
  a08=(a08+a16);
  a08=(a47*a08);
  a08=(a13*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a19*a08);
  a16=(a06+a06);
  a16=(a16*a05);
  a16=(a09*a16);
  a21=(a21*a16);
  a21=(a02*a21);
  a08=(a08+a21);
  a08=(a49*a08);
  a08=(a18*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a24*a08);
  a21=(a06+a06);
  a21=(a21*a05);
  a21=(a09*a21);
  a26=(a26*a21);
  a26=(a02*a26);
  a08=(a08+a26);
  a08=(a51*a08);
  a08=(a23*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a28*a08);
  a26=(a06+a06);
  a26=(a26*a05);
  a26=(a09*a26);
  a30=(a30*a26);
  a30=(a02*a30);
  a08=(a08+a30);
  a08=(a53*a08);
  a08=(a23*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a32*a08);
  a30=(a06+a06);
  a30=(a30*a05);
  a30=(a09*a30);
  a34=(a34*a30);
  a34=(a02*a34);
  a08=(a08+a34);
  a08=(a55*a08);
  a08=(a18*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a36*a08);
  a34=(a06+a06);
  a34=(a34*a05);
  a34=(a09*a34);
  a38=(a38*a34);
  a38=(a02*a38);
  a08=(a08+a38);
  a08=(a57*a08);
  a08=(a13*a08);
  a45=(a45+a08);
  a08=(a04*a05);
  a08=(a40*a08);
  a38=(a06+a06);
  a38=(a38*a05);
  a38=(a09*a38);
  a42=(a42*a38);
  a42=(a02*a42);
  a08=(a08+a42);
  a08=(a59*a08);
  a08=(a01*a08);
  a45=(a45+a08);
  a45=(a06*a45);
  a46=(a46*a05);
  a45=(a45+a46);
  if (res[1]!=0) res[1][6]=a45;
  if (res[1]!=0) res[1][7]=a11;
  a45=(a01*a44);
  a46=(a13*a47);
  a45=(a45+a46);
  a46=(a18*a49);
  a45=(a45+a46);
  a46=(a23*a51);
  a45=(a45+a46);
  a46=(a23*a53);
  a45=(a45+a46);
  a46=(a18*a55);
  a45=(a45+a46);
  a46=(a13*a57);
  a45=(a45+a46);
  a46=(a01*a59);
  a45=(a45+a46);
  a45=(a06*a45);
  if (res[1]!=0) res[1][8]=a45;
  a03=(a03*a06);
  a44=(a44*a03);
  a44=(a01*a44);
  a14=(a14*a06);
  a47=(a47*a14);
  a47=(a13*a47);
  a44=(a44+a47);
  a19=(a19*a06);
  a49=(a49*a19);
  a49=(a18*a49);
  a44=(a44+a49);
  a24=(a24*a06);
  a51=(a51*a24);
  a51=(a23*a51);
  a44=(a44+a51);
  a28=(a28*a06);
  a53=(a53*a28);
  a23=(a23*a53);
  a44=(a44+a23);
  a32=(a32*a06);
  a55=(a55*a32);
  a18=(a18*a55);
  a44=(a44+a18);
  a36=(a36*a06);
  a57=(a57*a36);
  a13=(a13*a57);
  a44=(a44+a13);
  a40=(a40*a06);
  a59=(a59*a40);
  a01=(a01*a59);
  a44=(a44+a01);
  a44=(a06*a44);
  if (res[1]!=0) res[1][9]=a44;
  a00=(a02*a00);
  if (res[1]!=0) res[1][10]=a00;
  a04=(a04*a05);
  a00=(a06+a06);
  a00=(a00*a05);
  a00=(a09*a00);
  a02=(a02*a00);
  a04=(a04+a02);
  if (res[1]!=0) res[1][11]=a04;
  if (res[1]!=0) res[1][12]=a11;
  if (res[1]!=0) res[1][13]=a06;
  if (res[1]!=0) res[1][14]=a06;
  a09=(a09*a05);
  if (res[1]!=0) res[1][15]=a09;
  if (res[1]!=0) res[1][16]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void ev9_path_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ev9_path_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int ev9_path_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ev9_path_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ev9_path_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ev9_path_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ev9_path_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ev9_path_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ev9_path_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
