import shlex
import sys

Import('env', 'arch')

gen = 'c_generated_code'
model = ['dyn_disc_phi_fun', 'dyn_disc_phi_fun_jac', 'dyn_disc_phi_fun_jac_hess']
sources = ([f'{gen}/acados_solver_ev9_path.c'] +
           [f'{gen}/ev9_path_model/ev9_path_{name}.c' for name in model])
headers = [f'{gen}/acados_solver_ev9_path.h', f'{gen}/ev9_path_model/ev9_path_model.h',
           f'{gen}/ev9_path_constraints/ev9_path_constraints.h']
build_env = env.Clone()
dependencies = [File('generate.py'), File('#third_party/acados/include/acados_c/ocp_nlp_interface.h')]
dependencies += Glob('#third_party/acados/acados_template/*.py')
dependencies += Glob('#third_party/acados/acados_template/c_templates_tera/*')
command = [sys.executable, File('generate.py').srcnode().abspath, '--generate-only', '--arch', arch, '--output', Dir(gen).abspath]
build_env.Command(sources + headers, dependencies, ' '.join(shlex.quote(arg) for arg in command))
build_env.Clean(sources + headers, Dir(gen))
build_env.Append(CCFLAGS=['-Wno-unused'])
build_env.Append(CPPPATH=[Dir(gen).abspath])
acados_relative = Dir('.').rel_path(Dir(f'#third_party/acados/{arch}/lib'))
if arch == 'Darwin':
  build_env.Append(LINKFLAGS=[f'-Wl,-rpath,@loader_path/{acados_relative}'])
else:
  build_env.Append(RPATH=[build_env.Literal(f'\\$$ORIGIN/{acados_relative}')], LINKFLAGS=['-Wl,--disable-new-dtags'])
build_env.SharedLibrary('ev9_path_mpc', sources + ['wrapper.c'], LIBS=['m', 'acados', 'hpipm', 'blasfeo'])
